// <auto-generated />
using System;
using CartaPromesa.Persistence.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CartaPromesa.Persistence.Migrations
{
    [DbContext(typeof(CartaPromesaDbContext))]
    partial class CartaPromesaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CartaPromesa.Domain.Models.Solicitud", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApellidoBeneficiario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApellidoOrdenante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("FechaSolicitud")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("FechaVencimiento")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreBeneficiario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreOrdenante")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Solicitudes");
                });
#pragma warning restore 612, 618
        }
    }
}
